/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

typedef volatile unsigned int vuint32_t ;
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
// register address
#define GPIOA_BASE 0x40010800
#define RCC_BASE   0x40021000
#define AFIO_BASE  0x40010000
#define EXTI_BASE  0x40010400
#define NVIC_BASE  0xE000E100


struct bit{
	vuint32_t bit_0:1;
	vuint32_t bit_1:1;
	vuint32_t bit_2:1;
	vuint32_t bit_3:1;
	vuint32_t bit_4:1;
	vuint32_t bit_5:1;
	vuint32_t bit_6:1;
	vuint32_t bit_7:1;
	vuint32_t bit_8:1;
	vuint32_t bit_9:1;
	vuint32_t bit_10:1;
	vuint32_t bit_11:1;
	vuint32_t bit_12:1;
	vuint32_t bit_13:1;
	vuint32_t bit_14:1;
	vuint32_t bit_15:1;
	vuint32_t bit_16:1;
	vuint32_t bit_17:1;
	vuint32_t bit_18:1;
	vuint32_t bit_19:1;
	vuint32_t bit_20:1;
	vuint32_t bit_21:1;
	vuint32_t bit_22:1;
	vuint32_t bit_23:1;
	vuint32_t bit_24:1;

};

union REGS{
	struct bit S_bit;
	vuint32_t ALL;
};
union REGS *GPIOA_CRH   =(union REGS *) (GPIOA_BASE + 0x04);
union REGS *GPIOA_ODR   =(union REGS *) (GPIOA_BASE + 0x0C);
union REGS *GPIOA_CRL   =(union REGS *) (GPIOA_BASE + 0x00);

union REGS *AFIO_EXTICR1  =(union REGS *) (AFIO_BASE + 0x00);

union REGS *EXTI_IMR  =(union REGS *) (EXTI_BASE + 0x00);
union REGS *EXTI_RTSR =(union REGS *) (EXTI_BASE + 0x08);
union REGS *EXTI_PR   =(union REGS *) (EXTI_BASE + 0x14);

union REGS *NVIC_ISERO   =(union REGS *) (NVIC_BASE + 0x0);

union REGS *RCC_APB2ENR =(union REGS *) (RCC_BASE + 0X18);
union REGS *RCC_APB2RSTR =(union REGS *) (RCC_BASE + 0X0C);

void clock_init()
{
	RCC_APB2RSTR->S_bit.bit_0=1;
	RCC_APB2RSTR->S_bit.bit_2=1;
}

void GPIO_init()
{
	//Init GPIOA
	//pin 13 out
	GPIOA_CRH->S_bit.bit_20=0;
	GPIOA_CRH->S_bit.bit_21=1;
	GPIOA_CRH->S_bit.bit_22=0;
	GPIOA_CRH->S_bit.bit_23=0;
	//pin 0 in
	GPIOA_CRL->S_bit.bit_2=1;
	GPIOA_CRL->S_bit.bit_0=0;
	GPIOA_CRL->S_bit.bit_1=0;
}

int main(void)
{
	clock_init();
	GPIO_init();

	//These bits are written by software to select the source input for EXTI0 external interrupt
	AFIO_EXTICR1->S_bit.bit_1=0;

	//1: Interrupt request from Line 0 is not masked
	EXTI_IMR->S_bit.bit_0=1;

	//1: Rising trigger enabled (for Event and Interrupt) for input line.
	EXTI_RTSR->S_bit.bit_0=1;

	//enable NVIC iqr 6 (EXTI0)
	NVIC_ISERO->S_bit.bit_6=1;

	while(1);
}

void EXTI0_IRQHandler()
{
	//toggle bit 13
	GPIOA_ODR->S_bit.bit_13^=1;

	//
	EXTI_PR->S_bit.bit_0=1;
}
