/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32 f103c6_gpio_driver.h"
#include "stm32 f103c6_USART_driver.h"


uint16_t ch;
void clock_init()
{
	RCC_GPIOA_CLOCK_EN();
	RCC_GPIOB_CLOCK_EN();
	RCC_AFIO_CLOCK_EN();
}

void UART_ISR()
{
	MCAL_UART_RECEIVE_DATA(USART1, &ch, disable);
	MCAL_UART_SEND_DATA(USART1, &ch, enable);
}


int main(void)
{
	clock_init();

	USART_config UART_Con;

	UART_Con.USART_MODE=USART_MODE_TX_RX;
	UART_Con.BaudRate=USART_BaudRate_115200;
	UART_Con.HW_Ctrol=USART_HW_FlowCtrl_NONE;
	UART_Con.IRQ_Enable=USART_IRQ_Enable_RXNE;
	UART_Con.data_len=USART_data_Length_8B;
	UART_Con.p_IRQ_call_back=UART_ISR;
	UART_Con.parity=USART_Parity_NONE;
	UART_Con.stop_bits=USART_StopBits_1;

	MCAL_UART_INIT(USART1, &UART_Con);
	MCAL_UART_GPIO_Set_Pins(USART1);

	while(1)
	{

	}
}


