/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32 f103c6_gpio_driver.h"

void clock_init()
{
	RCC_GPIOA_CLOCK_EN();
	RCC_GPIOB_CLOCK_EN() ;
}

void GPIO_init()
{
	GPIO_Pinconfig_t pin_con;

	//PA1 INPUT HIGH Z
	pin_con.GPIO_PinNumber=GPIO_PIN_1;
	pin_con.GPIO_MODE=GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA, &pin_con);

	//PA1 OUTPT PUSH PULL
	//SPEED 10M
	pin_con.GPIO_PinNumber=GPIO_PIN_1;
	pin_con.GPIO_MODE=GPIO_MODE_OUTPUT_PP;
	pin_con.GPIO_Output_Speed=GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &pin_con);

	//PA13 INPUT HIGH Z
	pin_con.GPIO_PinNumber=GPIO_PIN_13;
	pin_con.GPIO_MODE=GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA, &pin_con);

	//PA13 OUTPT PUSH PULL
	//SPEED 10M
	pin_con.GPIO_PinNumber=GPIO_PIN_13;
	pin_con.GPIO_MODE=GPIO_MODE_OUTPUT_PP;
	pin_con.GPIO_Output_Speed=GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &pin_con);

}

void wait()
{
	int i;
	for(i=0;i<200;i++);
}

int main(void)
{
	clock_init();
	GPIO_init();

	while(1)
	{
		if(MCAL_GPIO_Read_pin(GPIOA, GPIO_PIN_1)==0)
		{
			MCAL_GPIO_Toggle_pin(GPIOB, GPIO_PIN_1);
			while(MCAL_GPIO_Read_pin(GPIOA, GPIO_PIN_1)==0);
		}
		if(MCAL_GPIO_Read_pin(GPIOA, GPIO_PIN_13)==1)
		{
			MCAL_GPIO_Toggle_pin(GPIOB, GPIO_PIN_13);

		}
		wait();
	}
}


