/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

typedef volatile unsigned int vuint32_t ;
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
// register address
#define GPIOA_BASE 0x40010800
#define RCC_BASE   0x40021000
#define GPIOB_BASE 0x40010C00


struct bit{
	vuint32_t bit_0:1;
	vuint32_t bit_1:1;
	vuint32_t bit_2:1;
	vuint32_t bit_3:1;
	vuint32_t bit_4:1;
	vuint32_t bit_5:1;
	vuint32_t bit_6:1;
	vuint32_t bit_7:1;
	vuint32_t bit_8:1;
	vuint32_t bit_9:1;
	vuint32_t bit_10:1;
	vuint32_t bit_11:1;
	vuint32_t bit_12:1;
	vuint32_t bit_13:1;
	vuint32_t bit_14:1;
	vuint32_t bit_15:1;
	vuint32_t bit_16:1;
	vuint32_t bit_17:1;
	vuint32_t bit_18:1;
	vuint32_t bit_19:1;
	vuint32_t bit_20:1;
	vuint32_t bit_21:1;
	vuint32_t bit_22:1;
	vuint32_t bit_23:1;
	vuint32_t bit_24:1;

};

union REGS{
	struct bit S_bit;
	vuint32_t ALL;
};
union REGS *GPIOA_CRH   =(union REGS *) (GPIOA_BASE + 0x04);
union REGS *GPIOA_ODR   =(union REGS *) (GPIOA_BASE + 0x0C);
union REGS *GPIOA_CRL   =(union REGS *) (GPIOA_BASE + 0x00);
union REGS *GPIOA_IDR   =(union REGS *) (GPIOA_BASE + 0x08);


union REGS *GPIOB_CRH   =(union REGS *) (GPIOB_BASE + 0x04);
union REGS *GPIOB_ODR   =(union REGS *) (GPIOB_BASE + 0x0C);
union REGS *GPIOB_CRL   =(union REGS *) (GPIOB_BASE + 0x00);
union REGS *GPIOB_IDR   =(union REGS *) (GPIOB_BASE + 0x08);

union REGS *RCC_APB2ENR =(union REGS *) (RCC_BASE + 0X18);

void clock_init()
{
	RCC_APB2ENR->S_bit.bit_2=1;
	RCC_APB2ENR->S_bit.bit_3=1;
}

void GPIO_init()
{
	//pin 1 input
	GPIOA_CRL->ALL=0;
	//01: Floating input (reset state)
	GPIOA_CRL->S_bit.bit_6=1;
	//pin 13 input
	GPIOA_CRH->ALL=0;
	//01: Floating input (reset state)
	GPIOA_CRH->S_bit.bit_22=1;

	GPIOB_CRL->ALL=0;
	GPIOB_CRH->ALL=0;
	//01: Output mode, max speed 10 MHz.
	GPIOB_CRL->S_bit.bit_4=1;
	//00: General purpose output push-pull
	GPIOB_CRL->S_bit.bit_6=0;
	GPIOB_CRL->S_bit.bit_7=0;
	//01: Output mode, max speed 10 MHz.
	GPIOB_CRH->S_bit.bit_20=1;
	//00: General purpose output push-pull
	GPIOB_CRH->S_bit.bit_22=0;
	GPIOB_CRH->S_bit.bit_23=0;
}

void wait()
{
	int i;
	for(i=0;i<200;i++);
}

int main(void)
{
	clock_init();
	GPIO_init();

	while(1)
	{
		if((GPIOA_IDR->S_bit.bit_1)==0)
		{
			GPIOB_ODR->ALL ^=(1<<1);
			while(GPIOA_IDR->S_bit.bit_1==0);
		}
		if((GPIOA_IDR->S_bit.bit_13)==1)
		{
			GPIOB_ODR->ALL ^=(1<<13);

		}
		wait();
	}
}


